# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/program/code/clion/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /opt/program/code/clion/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /opt/work/c/skynet

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /opt/work/c/skynet

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/program/code/clion/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/opt/program/code/clion/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /opt/work/c/skynet/CMakeFiles /opt/work/c/skynet/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /opt/work/c/skynet/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gate

# Build rule for target.
gate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gate
.PHONY : gate

# fast build rule for target.
gate/fast:
	$(MAKE) -f CMakeFiles/gate.dir/build.make CMakeFiles/gate.dir/build
.PHONY : gate/fast

#=============================================================================
# Target rules for targets named skynet

# Build rule for target.
skynet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 skynet
.PHONY : skynet

# fast build rule for target.
skynet/fast:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/build
.PHONY : skynet/fast

#=============================================================================
# Target rules for targets named harbor

# Build rule for target.
harbor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 harbor
.PHONY : harbor

# fast build rule for target.
harbor/fast:
	$(MAKE) -f CMakeFiles/harbor.dir/build.make CMakeFiles/harbor.dir/build
.PHONY : harbor/fast

#=============================================================================
# Target rules for targets named logger

# Build rule for target.
logger: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 logger
.PHONY : logger

# fast build rule for target.
logger/fast:
	$(MAKE) -f CMakeFiles/logger.dir/build.make CMakeFiles/logger.dir/build
.PHONY : logger/fast

#=============================================================================
# Target rules for targets named snlua

# Build rule for target.
snlua: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 snlua
.PHONY : snlua

# fast build rule for target.
snlua/fast:
	$(MAKE) -f CMakeFiles/snlua.dir/build.make CMakeFiles/snlua.dir/build
.PHONY : snlua/fast

service-src/service_gate.o: service-src/service_gate.c.o

.PHONY : service-src/service_gate.o

# target to build an object file
service-src/service_gate.c.o:
	$(MAKE) -f CMakeFiles/gate.dir/build.make CMakeFiles/gate.dir/service-src/service_gate.c.o
.PHONY : service-src/service_gate.c.o

service-src/service_gate.i: service-src/service_gate.c.i

.PHONY : service-src/service_gate.i

# target to preprocess a source file
service-src/service_gate.c.i:
	$(MAKE) -f CMakeFiles/gate.dir/build.make CMakeFiles/gate.dir/service-src/service_gate.c.i
.PHONY : service-src/service_gate.c.i

service-src/service_gate.s: service-src/service_gate.c.s

.PHONY : service-src/service_gate.s

# target to generate assembly for a file
service-src/service_gate.c.s:
	$(MAKE) -f CMakeFiles/gate.dir/build.make CMakeFiles/gate.dir/service-src/service_gate.c.s
.PHONY : service-src/service_gate.c.s

service-src/service_harbor.o: service-src/service_harbor.c.o

.PHONY : service-src/service_harbor.o

# target to build an object file
service-src/service_harbor.c.o:
	$(MAKE) -f CMakeFiles/harbor.dir/build.make CMakeFiles/harbor.dir/service-src/service_harbor.c.o
.PHONY : service-src/service_harbor.c.o

service-src/service_harbor.i: service-src/service_harbor.c.i

.PHONY : service-src/service_harbor.i

# target to preprocess a source file
service-src/service_harbor.c.i:
	$(MAKE) -f CMakeFiles/harbor.dir/build.make CMakeFiles/harbor.dir/service-src/service_harbor.c.i
.PHONY : service-src/service_harbor.c.i

service-src/service_harbor.s: service-src/service_harbor.c.s

.PHONY : service-src/service_harbor.s

# target to generate assembly for a file
service-src/service_harbor.c.s:
	$(MAKE) -f CMakeFiles/harbor.dir/build.make CMakeFiles/harbor.dir/service-src/service_harbor.c.s
.PHONY : service-src/service_harbor.c.s

service-src/service_logger.o: service-src/service_logger.c.o

.PHONY : service-src/service_logger.o

# target to build an object file
service-src/service_logger.c.o:
	$(MAKE) -f CMakeFiles/logger.dir/build.make CMakeFiles/logger.dir/service-src/service_logger.c.o
.PHONY : service-src/service_logger.c.o

service-src/service_logger.i: service-src/service_logger.c.i

.PHONY : service-src/service_logger.i

# target to preprocess a source file
service-src/service_logger.c.i:
	$(MAKE) -f CMakeFiles/logger.dir/build.make CMakeFiles/logger.dir/service-src/service_logger.c.i
.PHONY : service-src/service_logger.c.i

service-src/service_logger.s: service-src/service_logger.c.s

.PHONY : service-src/service_logger.s

# target to generate assembly for a file
service-src/service_logger.c.s:
	$(MAKE) -f CMakeFiles/logger.dir/build.make CMakeFiles/logger.dir/service-src/service_logger.c.s
.PHONY : service-src/service_logger.c.s

service-src/service_snlua.o: service-src/service_snlua.c.o

.PHONY : service-src/service_snlua.o

# target to build an object file
service-src/service_snlua.c.o:
	$(MAKE) -f CMakeFiles/snlua.dir/build.make CMakeFiles/snlua.dir/service-src/service_snlua.c.o
.PHONY : service-src/service_snlua.c.o

service-src/service_snlua.i: service-src/service_snlua.c.i

.PHONY : service-src/service_snlua.i

# target to preprocess a source file
service-src/service_snlua.c.i:
	$(MAKE) -f CMakeFiles/snlua.dir/build.make CMakeFiles/snlua.dir/service-src/service_snlua.c.i
.PHONY : service-src/service_snlua.c.i

service-src/service_snlua.s: service-src/service_snlua.c.s

.PHONY : service-src/service_snlua.s

# target to generate assembly for a file
service-src/service_snlua.c.s:
	$(MAKE) -f CMakeFiles/snlua.dir/build.make CMakeFiles/snlua.dir/service-src/service_snlua.c.s
.PHONY : service-src/service_snlua.c.s

skynet-src/malloc_hook.o: skynet-src/malloc_hook.c.o

.PHONY : skynet-src/malloc_hook.o

# target to build an object file
skynet-src/malloc_hook.c.o:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/malloc_hook.c.o
.PHONY : skynet-src/malloc_hook.c.o

skynet-src/malloc_hook.i: skynet-src/malloc_hook.c.i

.PHONY : skynet-src/malloc_hook.i

# target to preprocess a source file
skynet-src/malloc_hook.c.i:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/malloc_hook.c.i
.PHONY : skynet-src/malloc_hook.c.i

skynet-src/malloc_hook.s: skynet-src/malloc_hook.c.s

.PHONY : skynet-src/malloc_hook.s

# target to generate assembly for a file
skynet-src/malloc_hook.c.s:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/malloc_hook.c.s
.PHONY : skynet-src/malloc_hook.c.s

skynet-src/skynet_daemon.o: skynet-src/skynet_daemon.c.o

.PHONY : skynet-src/skynet_daemon.o

# target to build an object file
skynet-src/skynet_daemon.c.o:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/skynet_daemon.c.o
.PHONY : skynet-src/skynet_daemon.c.o

skynet-src/skynet_daemon.i: skynet-src/skynet_daemon.c.i

.PHONY : skynet-src/skynet_daemon.i

# target to preprocess a source file
skynet-src/skynet_daemon.c.i:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/skynet_daemon.c.i
.PHONY : skynet-src/skynet_daemon.c.i

skynet-src/skynet_daemon.s: skynet-src/skynet_daemon.c.s

.PHONY : skynet-src/skynet_daemon.s

# target to generate assembly for a file
skynet-src/skynet_daemon.c.s:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/skynet_daemon.c.s
.PHONY : skynet-src/skynet_daemon.c.s

skynet-src/skynet_env.o: skynet-src/skynet_env.c.o

.PHONY : skynet-src/skynet_env.o

# target to build an object file
skynet-src/skynet_env.c.o:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/skynet_env.c.o
.PHONY : skynet-src/skynet_env.c.o

skynet-src/skynet_env.i: skynet-src/skynet_env.c.i

.PHONY : skynet-src/skynet_env.i

# target to preprocess a source file
skynet-src/skynet_env.c.i:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/skynet_env.c.i
.PHONY : skynet-src/skynet_env.c.i

skynet-src/skynet_env.s: skynet-src/skynet_env.c.s

.PHONY : skynet-src/skynet_env.s

# target to generate assembly for a file
skynet-src/skynet_env.c.s:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/skynet_env.c.s
.PHONY : skynet-src/skynet_env.c.s

skynet-src/skynet_error.o: skynet-src/skynet_error.c.o

.PHONY : skynet-src/skynet_error.o

# target to build an object file
skynet-src/skynet_error.c.o:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/skynet_error.c.o
.PHONY : skynet-src/skynet_error.c.o

skynet-src/skynet_error.i: skynet-src/skynet_error.c.i

.PHONY : skynet-src/skynet_error.i

# target to preprocess a source file
skynet-src/skynet_error.c.i:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/skynet_error.c.i
.PHONY : skynet-src/skynet_error.c.i

skynet-src/skynet_error.s: skynet-src/skynet_error.c.s

.PHONY : skynet-src/skynet_error.s

# target to generate assembly for a file
skynet-src/skynet_error.c.s:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/skynet_error.c.s
.PHONY : skynet-src/skynet_error.c.s

skynet-src/skynet_handle.o: skynet-src/skynet_handle.c.o

.PHONY : skynet-src/skynet_handle.o

# target to build an object file
skynet-src/skynet_handle.c.o:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/skynet_handle.c.o
.PHONY : skynet-src/skynet_handle.c.o

skynet-src/skynet_handle.i: skynet-src/skynet_handle.c.i

.PHONY : skynet-src/skynet_handle.i

# target to preprocess a source file
skynet-src/skynet_handle.c.i:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/skynet_handle.c.i
.PHONY : skynet-src/skynet_handle.c.i

skynet-src/skynet_handle.s: skynet-src/skynet_handle.c.s

.PHONY : skynet-src/skynet_handle.s

# target to generate assembly for a file
skynet-src/skynet_handle.c.s:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/skynet_handle.c.s
.PHONY : skynet-src/skynet_handle.c.s

skynet-src/skynet_harbor.o: skynet-src/skynet_harbor.c.o

.PHONY : skynet-src/skynet_harbor.o

# target to build an object file
skynet-src/skynet_harbor.c.o:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/skynet_harbor.c.o
.PHONY : skynet-src/skynet_harbor.c.o

skynet-src/skynet_harbor.i: skynet-src/skynet_harbor.c.i

.PHONY : skynet-src/skynet_harbor.i

# target to preprocess a source file
skynet-src/skynet_harbor.c.i:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/skynet_harbor.c.i
.PHONY : skynet-src/skynet_harbor.c.i

skynet-src/skynet_harbor.s: skynet-src/skynet_harbor.c.s

.PHONY : skynet-src/skynet_harbor.s

# target to generate assembly for a file
skynet-src/skynet_harbor.c.s:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/skynet_harbor.c.s
.PHONY : skynet-src/skynet_harbor.c.s

skynet-src/skynet_log.o: skynet-src/skynet_log.c.o

.PHONY : skynet-src/skynet_log.o

# target to build an object file
skynet-src/skynet_log.c.o:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/skynet_log.c.o
.PHONY : skynet-src/skynet_log.c.o

skynet-src/skynet_log.i: skynet-src/skynet_log.c.i

.PHONY : skynet-src/skynet_log.i

# target to preprocess a source file
skynet-src/skynet_log.c.i:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/skynet_log.c.i
.PHONY : skynet-src/skynet_log.c.i

skynet-src/skynet_log.s: skynet-src/skynet_log.c.s

.PHONY : skynet-src/skynet_log.s

# target to generate assembly for a file
skynet-src/skynet_log.c.s:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/skynet_log.c.s
.PHONY : skynet-src/skynet_log.c.s

skynet-src/skynet_main.o: skynet-src/skynet_main.c.o

.PHONY : skynet-src/skynet_main.o

# target to build an object file
skynet-src/skynet_main.c.o:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/skynet_main.c.o
.PHONY : skynet-src/skynet_main.c.o

skynet-src/skynet_main.i: skynet-src/skynet_main.c.i

.PHONY : skynet-src/skynet_main.i

# target to preprocess a source file
skynet-src/skynet_main.c.i:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/skynet_main.c.i
.PHONY : skynet-src/skynet_main.c.i

skynet-src/skynet_main.s: skynet-src/skynet_main.c.s

.PHONY : skynet-src/skynet_main.s

# target to generate assembly for a file
skynet-src/skynet_main.c.s:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/skynet_main.c.s
.PHONY : skynet-src/skynet_main.c.s

skynet-src/skynet_module.o: skynet-src/skynet_module.c.o

.PHONY : skynet-src/skynet_module.o

# target to build an object file
skynet-src/skynet_module.c.o:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/skynet_module.c.o
.PHONY : skynet-src/skynet_module.c.o

skynet-src/skynet_module.i: skynet-src/skynet_module.c.i

.PHONY : skynet-src/skynet_module.i

# target to preprocess a source file
skynet-src/skynet_module.c.i:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/skynet_module.c.i
.PHONY : skynet-src/skynet_module.c.i

skynet-src/skynet_module.s: skynet-src/skynet_module.c.s

.PHONY : skynet-src/skynet_module.s

# target to generate assembly for a file
skynet-src/skynet_module.c.s:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/skynet_module.c.s
.PHONY : skynet-src/skynet_module.c.s

skynet-src/skynet_monitor.o: skynet-src/skynet_monitor.c.o

.PHONY : skynet-src/skynet_monitor.o

# target to build an object file
skynet-src/skynet_monitor.c.o:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/skynet_monitor.c.o
.PHONY : skynet-src/skynet_monitor.c.o

skynet-src/skynet_monitor.i: skynet-src/skynet_monitor.c.i

.PHONY : skynet-src/skynet_monitor.i

# target to preprocess a source file
skynet-src/skynet_monitor.c.i:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/skynet_monitor.c.i
.PHONY : skynet-src/skynet_monitor.c.i

skynet-src/skynet_monitor.s: skynet-src/skynet_monitor.c.s

.PHONY : skynet-src/skynet_monitor.s

# target to generate assembly for a file
skynet-src/skynet_monitor.c.s:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/skynet_monitor.c.s
.PHONY : skynet-src/skynet_monitor.c.s

skynet-src/skynet_mq.o: skynet-src/skynet_mq.c.o

.PHONY : skynet-src/skynet_mq.o

# target to build an object file
skynet-src/skynet_mq.c.o:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/skynet_mq.c.o
.PHONY : skynet-src/skynet_mq.c.o

skynet-src/skynet_mq.i: skynet-src/skynet_mq.c.i

.PHONY : skynet-src/skynet_mq.i

# target to preprocess a source file
skynet-src/skynet_mq.c.i:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/skynet_mq.c.i
.PHONY : skynet-src/skynet_mq.c.i

skynet-src/skynet_mq.s: skynet-src/skynet_mq.c.s

.PHONY : skynet-src/skynet_mq.s

# target to generate assembly for a file
skynet-src/skynet_mq.c.s:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/skynet_mq.c.s
.PHONY : skynet-src/skynet_mq.c.s

skynet-src/skynet_server.o: skynet-src/skynet_server.c.o

.PHONY : skynet-src/skynet_server.o

# target to build an object file
skynet-src/skynet_server.c.o:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/skynet_server.c.o
.PHONY : skynet-src/skynet_server.c.o

skynet-src/skynet_server.i: skynet-src/skynet_server.c.i

.PHONY : skynet-src/skynet_server.i

# target to preprocess a source file
skynet-src/skynet_server.c.i:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/skynet_server.c.i
.PHONY : skynet-src/skynet_server.c.i

skynet-src/skynet_server.s: skynet-src/skynet_server.c.s

.PHONY : skynet-src/skynet_server.s

# target to generate assembly for a file
skynet-src/skynet_server.c.s:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/skynet_server.c.s
.PHONY : skynet-src/skynet_server.c.s

skynet-src/skynet_socket.o: skynet-src/skynet_socket.c.o

.PHONY : skynet-src/skynet_socket.o

# target to build an object file
skynet-src/skynet_socket.c.o:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/skynet_socket.c.o
.PHONY : skynet-src/skynet_socket.c.o

skynet-src/skynet_socket.i: skynet-src/skynet_socket.c.i

.PHONY : skynet-src/skynet_socket.i

# target to preprocess a source file
skynet-src/skynet_socket.c.i:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/skynet_socket.c.i
.PHONY : skynet-src/skynet_socket.c.i

skynet-src/skynet_socket.s: skynet-src/skynet_socket.c.s

.PHONY : skynet-src/skynet_socket.s

# target to generate assembly for a file
skynet-src/skynet_socket.c.s:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/skynet_socket.c.s
.PHONY : skynet-src/skynet_socket.c.s

skynet-src/skynet_start.o: skynet-src/skynet_start.c.o

.PHONY : skynet-src/skynet_start.o

# target to build an object file
skynet-src/skynet_start.c.o:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/skynet_start.c.o
.PHONY : skynet-src/skynet_start.c.o

skynet-src/skynet_start.i: skynet-src/skynet_start.c.i

.PHONY : skynet-src/skynet_start.i

# target to preprocess a source file
skynet-src/skynet_start.c.i:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/skynet_start.c.i
.PHONY : skynet-src/skynet_start.c.i

skynet-src/skynet_start.s: skynet-src/skynet_start.c.s

.PHONY : skynet-src/skynet_start.s

# target to generate assembly for a file
skynet-src/skynet_start.c.s:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/skynet_start.c.s
.PHONY : skynet-src/skynet_start.c.s

skynet-src/skynet_timer.o: skynet-src/skynet_timer.c.o

.PHONY : skynet-src/skynet_timer.o

# target to build an object file
skynet-src/skynet_timer.c.o:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/skynet_timer.c.o
.PHONY : skynet-src/skynet_timer.c.o

skynet-src/skynet_timer.i: skynet-src/skynet_timer.c.i

.PHONY : skynet-src/skynet_timer.i

# target to preprocess a source file
skynet-src/skynet_timer.c.i:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/skynet_timer.c.i
.PHONY : skynet-src/skynet_timer.c.i

skynet-src/skynet_timer.s: skynet-src/skynet_timer.c.s

.PHONY : skynet-src/skynet_timer.s

# target to generate assembly for a file
skynet-src/skynet_timer.c.s:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/skynet_timer.c.s
.PHONY : skynet-src/skynet_timer.c.s

skynet-src/socket_server.o: skynet-src/socket_server.c.o

.PHONY : skynet-src/socket_server.o

# target to build an object file
skynet-src/socket_server.c.o:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/socket_server.c.o
.PHONY : skynet-src/socket_server.c.o

skynet-src/socket_server.i: skynet-src/socket_server.c.i

.PHONY : skynet-src/socket_server.i

# target to preprocess a source file
skynet-src/socket_server.c.i:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/socket_server.c.i
.PHONY : skynet-src/socket_server.c.i

skynet-src/socket_server.s: skynet-src/socket_server.c.s

.PHONY : skynet-src/socket_server.s

# target to generate assembly for a file
skynet-src/socket_server.c.s:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/skynet-src/socket_server.c.s
.PHONY : skynet-src/socket_server.c.s

util/debug.o: util/debug.c.o

.PHONY : util/debug.o

# target to build an object file
util/debug.c.o:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/util/debug.c.o
.PHONY : util/debug.c.o

util/debug.i: util/debug.c.i

.PHONY : util/debug.i

# target to preprocess a source file
util/debug.c.i:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/util/debug.c.i
.PHONY : util/debug.c.i

util/debug.s: util/debug.c.s

.PHONY : util/debug.s

# target to generate assembly for a file
util/debug.c.s:
	$(MAKE) -f CMakeFiles/skynet.dir/build.make CMakeFiles/skynet.dir/util/debug.c.s
.PHONY : util/debug.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... gate"
	@echo "... skynet"
	@echo "... edit_cache"
	@echo "... harbor"
	@echo "... logger"
	@echo "... snlua"
	@echo "... service-src/service_gate.o"
	@echo "... service-src/service_gate.i"
	@echo "... service-src/service_gate.s"
	@echo "... service-src/service_harbor.o"
	@echo "... service-src/service_harbor.i"
	@echo "... service-src/service_harbor.s"
	@echo "... service-src/service_logger.o"
	@echo "... service-src/service_logger.i"
	@echo "... service-src/service_logger.s"
	@echo "... service-src/service_snlua.o"
	@echo "... service-src/service_snlua.i"
	@echo "... service-src/service_snlua.s"
	@echo "... skynet-src/malloc_hook.o"
	@echo "... skynet-src/malloc_hook.i"
	@echo "... skynet-src/malloc_hook.s"
	@echo "... skynet-src/skynet_daemon.o"
	@echo "... skynet-src/skynet_daemon.i"
	@echo "... skynet-src/skynet_daemon.s"
	@echo "... skynet-src/skynet_env.o"
	@echo "... skynet-src/skynet_env.i"
	@echo "... skynet-src/skynet_env.s"
	@echo "... skynet-src/skynet_error.o"
	@echo "... skynet-src/skynet_error.i"
	@echo "... skynet-src/skynet_error.s"
	@echo "... skynet-src/skynet_handle.o"
	@echo "... skynet-src/skynet_handle.i"
	@echo "... skynet-src/skynet_handle.s"
	@echo "... skynet-src/skynet_harbor.o"
	@echo "... skynet-src/skynet_harbor.i"
	@echo "... skynet-src/skynet_harbor.s"
	@echo "... skynet-src/skynet_log.o"
	@echo "... skynet-src/skynet_log.i"
	@echo "... skynet-src/skynet_log.s"
	@echo "... skynet-src/skynet_main.o"
	@echo "... skynet-src/skynet_main.i"
	@echo "... skynet-src/skynet_main.s"
	@echo "... skynet-src/skynet_module.o"
	@echo "... skynet-src/skynet_module.i"
	@echo "... skynet-src/skynet_module.s"
	@echo "... skynet-src/skynet_monitor.o"
	@echo "... skynet-src/skynet_monitor.i"
	@echo "... skynet-src/skynet_monitor.s"
	@echo "... skynet-src/skynet_mq.o"
	@echo "... skynet-src/skynet_mq.i"
	@echo "... skynet-src/skynet_mq.s"
	@echo "... skynet-src/skynet_server.o"
	@echo "... skynet-src/skynet_server.i"
	@echo "... skynet-src/skynet_server.s"
	@echo "... skynet-src/skynet_socket.o"
	@echo "... skynet-src/skynet_socket.i"
	@echo "... skynet-src/skynet_socket.s"
	@echo "... skynet-src/skynet_start.o"
	@echo "... skynet-src/skynet_start.i"
	@echo "... skynet-src/skynet_start.s"
	@echo "... skynet-src/skynet_timer.o"
	@echo "... skynet-src/skynet_timer.i"
	@echo "... skynet-src/skynet_timer.s"
	@echo "... skynet-src/socket_server.o"
	@echo "... skynet-src/socket_server.i"
	@echo "... skynet-src/socket_server.s"
	@echo "... util/debug.o"
	@echo "... util/debug.i"
	@echo "... util/debug.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

